'use strict';
const {World,roster,profiles,resolve,find,random}=KasuBattle;
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const parse=s=>[...new Set(s.split(/[,，、\n]/).map(n=>n.trim()).filter(Boolean))];
const storeKey='kasukou-battle-v1';let overrides=Object.create(null),uniformSkill='',world=null,running=false,started=false,last=null,acc=0,raf=0,lastList=-1,editedName='',visible=profiles;
const sample=['プラス','ユージ','ランス','コンケ','ルサイ','ツクリ','ドーマ','ヒヨコ'];
function persist(){try{localStorage.setItem(storeKey,JSON.stringify({names:$('names').value,overrides,seed:$('seed').value,suddenDeath:$('sudden-death').checked}));}catch{}}
function load(){try{const s=JSON.parse(localStorage.getItem(storeKey)||'null');if(s){if(typeof s.names==='string')$('names').value=s.names;if(typeof s.seed==='string')$('seed').value=s.seed;if(typeof s.suddenDeath==='boolean')$('sudden-death').checked=s.suddenDeath;
 for(const [n,v] of Object.entries(s.overrides||{}))if(v&&profiles.some(p=>p.id===v.skill)&&Number.isFinite(v.atk)&&v.atk>=1&&v.atk<=1000&&Number.isFinite(v.hp)&&v.hp>=1&&v.hp<=100000&&Number.isFinite(v.speed)&&v.speed>=.1&&v.speed<=30)overrides[n]=v;}}
 catch{}if(!$('names').value)$('names').value=sample.join('、');}
function status(){const ns=parse($('names').value),known=ns.filter(find).length;$('mode-label').textContent=ns.length>0&&ns.length<=5?'少人数モード · 狭い会場 / 2倍表示':ns.length>=6&&ns.length<=20?'中人数モード · 中くらいの会場 / 1.5倍表示':'通常モード · 時間・生存者数に応じて縮小';$('sudden-caption').textContent=$('sudden-death').checked?'50秒でサドンデス':'サドンデスなし（180秒で時間切れ）';$('start').disabled=ns.length<2||ns.length>60;$('input-status').textContent=ns.length>60?'60人まで参加できます。人数を減らしてください。':`${ns.length}人選択 / 名鑑キャラ ${known}人・自由入力 ${ns.length-known}人`;}
function matchOverrides(names){if(!uniformSkill)return overrides;const result=Object.create(null);for(const name of names)result[name]={...overrides[name],skill:uniformSkill};return result;}
function uniformStatus(){const p=profiles.find(p=>p.id===uniformSkill);$('uniform-status').textContent=p?`全員共通：${p.name} — ${p.title}（一時適用中）`:'現在は各キャラの能力';$('uniform-clear').disabled=!p;}
function preview(){status();uniformStatus();persist();if(started)return;const ns=parse($('names').value);world=ns.length&&ns.length<=60?new World(ns,{seed:$('seed').value.trim()||'preview',overrides:matchOverrides(ns),suddenDeath:$('sudden-death').checked}):null;renderList();draw();}
function setNames(ns){$('names').value=ns.join('、');preview();}
function rosterRandom(list,n=20,includeFinal=false){const rng=random(Date.now()+Math.random());const a=list.filter(p=>p.id!=='empress'&&(includeFinal||!p.finalMode));for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a.slice(0,n).map(p=>p.name);}
const iconAtlas=KASU_ICONS,facePaths=new Map(),faceSheet=new Image();let facesReady=false;
const clipDefs=document.createElementNS('http://www.w3.org/2000/svg','svg');clipDefs.setAttribute('width','0');clipDefs.setAttribute('height','0');clipDefs.setAttribute('aria-hidden','true');clipDefs.style.position='absolute';clipDefs.innerHTML='<defs>'+Object.entries(iconAtlas.characters).map(([id,face])=>`<clipPath id="face-${id}" clipPathUnits="objectBoundingBox"><path d="${face.clip}"/></clipPath>`).join('')+'</defs>';document.body.append(clipDefs);
faceSheet.onload=()=>{facesReady=true;draw();};faceSheet.onerror=()=>{document.documentElement.classList.add('icons-unavailable');draw();};faceSheet.src=iconAtlas.src;
function portrait(p,size){const face=p&&iconAtlas.characters[p.baseId||p.id];if(!face)return '';const [x,y,w,h]=face.rect,m=Math.max(w,h);return `<span class="portrait" data-face="${p.id}" data-fallback="${esc(p.icon)}" role="img" aria-label="${esc(p.name)}"${size?' style="--icon-size:'+size+'px"':''}><span class="face-sprite" style="width:calc(var(--icon-size)*${w/m});height:calc(var(--icon-size)*${h/m});background-size:calc(var(--icon-size)*${iconAtlas.width/m}) calc(var(--icon-size)*${iconAtlas.height/m});background-position:calc(var(--icon-size)*${-x/m}) calc(var(--icon-size)*${-y/m});clip-path:url(#face-${p.baseId||p.id})"></span></span>`;}
function drawFace(p,x,y,size){const face=p&&iconAtlas.characters[p.baseId||p.id];if(!facesReady||!face)return false;const [sx,sy,sw,sh]=face.rect,m=Math.max(sw,sh),w=size*sw/m,h=size*sh/m;let path=facePaths.get(p.id);if(!path){path=new Path2D(face.clip);facePaths.set(p.id,path);}ctx.save();ctx.translate(x-w/2,y-h/2);ctx.scale(w,h);ctx.clip(path);ctx.drawImage(faceSheet,sx,sy,sw,sh,0,0,1,1);ctx.restore();return true;}
function powerSummary(f){return f.powers.map(p=>{const a=profiles.find(a=>a.id===p.id);return a?a.name+'：'+a.title:p.id;}).join(' ／ ');}
function renderList(){const fs=world?world.units.filter(f=>!f.minion):[];const ordered=[...fs].sort((a,b)=>Number(b.alive)-Number(a.alive)||(a.alive?b.hp-a.hp:(b.deathTime||0)-(a.deathTime||0)));
 $('alive').textContent=`${fs.filter(f=>f.alive).length} / ${fs.length}`;
 const focused=document.activeElement?.dataset.name;
 $('participants').innerHTML=ordered.map(f=>{const p=profiles.find(p=>p.id===f.skill);return `<button class="participant ${f.alive?'':'dead'}" data-name="${esc(f.name)}" title="${esc((p?.desc||'通常戦闘')+(f.skill==='empress'?' / 能力：'+powerSummary(f):''))}">${portrait(f.profile)||`<span class="symbol">${p?.icon||'♟'}</span>`}<span class="p-info"><span class="p-name"><strong>${esc(f.name)}</strong><small>${f.profile?'G '+esc(f.profile.grade):'FREE'}</small></span><span class="p-ability">${esc(p?.title||'通常戦闘')}${f.powers.length>1?' ＋'+(f.powers.length-1):''}</span><span class="hp-track"><i style="width:${Math.max(0,f.hp/f.maxHp*100)}%"></i></span><span class="p-stats">HP ${Math.ceil(f.hp)} / ${Math.ceil(f.maxHp)}　ATK ${Math.round(f.atk)}　SPD ${f.speed.toFixed(1)}${f.shield?'　盾 '+Math.round(f.shield):''}</span></span></button>`;}).join('');
 for(const img of $('participants').querySelectorAll('img'))img.onerror=()=>{img.style.visibility='hidden';};
 if(focused){const el=[...$('participants').querySelectorAll('button')].find(x=>x.dataset.name===focused);el?.focus({preventScroll:true});}
 $('log').replaceChildren(...(started&&world?world.events.slice(-30).reverse():[]).map(e=>{const row=document.createElement('div');row.className='log-row';const t=document.createElement('time');t.textContent=formatTime(e.time);row.append(t,document.createTextNode(e.text));return row;}));
}
function formatTime(t){return String(Math.floor(t/60)).padStart(2,'0')+':'+String(Math.floor(t%60)).padStart(2,'0');}
const canvas=$('arena'),ctx=canvas.getContext('2d');
function draw(){ctx.clearRect(0,0,800,800);ctx.save();if(world&&world.viewScale>1){ctx.translate(400,400);ctx.scale(world.viewScale,world.viewScale);ctx.translate(-400,-400);}ctx.fillStyle='#12190f';ctx.fillRect(0,0,800,800);ctx.strokeStyle='#24301f';ctx.lineWidth=1;
 for(let i=0;i<=800;i+=40){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,800);ctx.moveTo(0,i);ctx.lineTo(800,i);ctx.stroke();}
 const r=world?.radius||385;ctx.beginPath();ctx.arc(400,400,r,0,Math.PI*2);ctx.fillStyle='#202c1b';ctx.fill();ctx.strokeStyle=world?.sudden?'#c35c4f':'#8d8559';ctx.lineWidth=3;ctx.stroke();
 for(const rad of [r*.66,r*.33]){ctx.beginPath();ctx.arc(400,400,rad,0,Math.PI*2);ctx.strokeStyle='#3a4730';ctx.lineWidth=1;ctx.stroke();}
 ctx.fillStyle='#46503c';ctx.font='600 32px Georgia';ctx.textAlign='center';ctx.fillText('K',400,410);
 if(!world){ctx.restore();return;}
 for(const z of world.zones){ctx.beginPath();ctx.arc(z.x,z.y,z.r,0,Math.PI*2);ctx.fillStyle={bomb:'#c36a3744',gate:'#c590db66',rain:'#85b9da33',snow:'#bfdffb44',gravity:'#9b84c055'}[z.kind]||'#b6c39433';ctx.fill();ctx.strokeStyle='#a2b17c';ctx.lineWidth=1;ctx.stroke();}
 for(const s of world.shots){ctx.fillStyle='#e6c87e';ctx.font='18px system-ui';ctx.fillText(s.icon,s.x,s.y);}
 for(const f of world.units){if(!f.alive)continue;const p=profiles.find(p=>p.id===f.skill);ctx.globalAlpha=world.has(f,'hidden')?.3:1;ctx.beginPath();ctx.arc(f.x,f.y,f.radius,0,Math.PI*2);ctx.fillStyle=f.minion?'#596149':f.profile?'#31432a':'#43516b';ctx.fill();ctx.strokeStyle=world.has(f,'seal')?'#888':world.has(f,'invulnerable')?'#f6dc86':f.shield?'#88c4d1':world.has(f,'stone')?'#999':p?.grade==='5'?'#d6b86e':'#819971';ctx.lineWidth=world.has(f,'invulnerable')?4:2;ctx.stroke();
 ctx.font=`${Math.round(f.radius*1.1)}px system-ui`;ctx.fillStyle='#eeefd8';ctx.textAlign='center';const sym=f.minion?({golem:'◆',machine:'⚙',animal:'🐦',clone:'◌',diamond:'◆'}[f.kind]||'•'):p?.icon||'♟';if(f.minion||!drawFace(f.profile||p,f.x,f.y,f.radius*2.2))ctx.fillText(sym,f.x,f.y+f.radius*.35);
 ctx.globalAlpha=1;ctx.font='10px system-ui';ctx.fillStyle='#e2e6d7';ctx.fillText([...f.name].slice(0,12).join(''),f.x,f.y+f.radius+13);const bw=36;ctx.fillStyle='#192015';ctx.fillRect(f.x-bw/2,f.y-f.radius-9,bw,4);ctx.fillStyle='#a6c887';ctx.fillRect(f.x-bw/2,f.y-f.radius-9,bw*Math.max(0,f.hp/f.maxHp),4);
 if(world.has(f,'air')){ctx.strokeStyle='#a0c7e5';ctx.beginPath();ctx.arc(f.x,f.y,f.radius+5,0,Math.PI*2);ctx.stroke();}}
 for(const e of world.effects){ctx.globalAlpha=Math.min(1,(e.end-world.time)*2);ctx.font='12px system-ui';ctx.fillStyle=e.color;ctx.fillText(e.text,e.x,e.y-25-(.8-(e.end-world.time))*20);}ctx.globalAlpha=1;ctx.restore();
}
function frame(ts){raf=0;if(!running)return;if(last===null)last=ts;acc+=Math.min((ts-last)/1000,.12)*Number($('speed').value);last=ts;while(acc>=1/60&&running&&!world.finished){world.step();acc-=1/60;}draw();$('time').textContent=formatTime(world.time);if(world.time-lastList>.25){renderList();lastList=world.time;}if(world.finished){finish();return;}raf=requestAnimationFrame(frame);}
function halt(){running=false;if(raf)cancelAnimationFrame(raf);raf=0;last=null;acc=0;}
function start(){const ns=parse($('names').value);if(ns.length<2||ns.length>60)return;halt();const seed=$('seed').value.trim()||String(Date.now())+'-'+Math.random().toString(36).slice(2,7);world=new World(ns,{seed,overrides:matchOverrides(ns),suddenDeath:$('sudden-death').checked});started=true;running=true;lastList=-1;$('setup').classList.add('hidden');$('result').classList.add('hidden');canvas.parentElement.classList.add('playing');$('pause').disabled=false;$('pause').textContent='一時停止';$('stop').disabled=false;$('match-state').textContent='戦闘中';$('seed-display').textContent='seed: '+seed;$('seed-display').title=seed;$('time').textContent='00:00';persist();renderList();raf=requestAnimationFrame(frame);}
function killRanking(){const fighters=world.units.filter(f=>!f.minion).sort((a,b)=>b.kills-a.kills||a.id-b.id);let rank=0;return fighters.slice(0,5).map((f,i)=>{if(i===0||f.kills!==fighters[i-1].kills)rank=i+1;return `<li class="kill-row" data-rank="${rank}"><span class="kill-rank">${rank}位</span>${portrait(f.profile||profiles.find(p=>p.id===f.skill),28)}<strong class="kill-name">${esc(f.name)}</strong><span class="kill-count">${f.kills}キル</span></li>`;}).join('');}
function survivalRanking(){const fighters=world.units.filter(f=>!f.minion).sort((a,b)=>Number(b.alive)-Number(a.alive)||((b.deathTime??0)-(a.deathTime??0))||a.id-b.id);let rank=0;return fighters.slice(0,5).map((f,i)=>{const previous=fighters[i-1];if(i===0||f.alive!==previous.alive||(!f.alive&&(f.deathTime??0)!==(previous.deathTime??0)))rank=i+1;const time=f.alive?world.result.time:(f.deathTime??0);return `<li class="survival-row" data-rank="${rank}"><span class="survival-rank">${rank}位</span>${portrait(f.profile||profiles.find(p=>p.id===f.skill),28)}<strong class="survival-name">${esc(f.name)}</strong><span class="survival-time">${time.toFixed(1)}秒${f.alive?'・生存':''}</span></li>`;}).join('');}
function finish(){halt();renderList();$('pause').disabled=true;$('stop').disabled=false;const r=world.result,w=r.winner;$('match-state').textContent='試合終了';$('result-title').textContent=w?'WINNER':r.draw?'DRAW':'TIME LIMIT';$('winner-icon').innerHTML=w?portrait(w.profile||profiles.find(p=>p.id===w.skill),90)||'♟':'⚖';$('winner-name').textContent=w?w.name:r.draw?'全員脱落':'180秒・決着なし';$('result-detail').textContent=w?`${formatTime(r.time)} / 撃破 ${w.kills}人 / 与ダメージ ${Math.round(w.damage)} / 能力 ${w.powers.length}種`:r.timeout?'残った参加者で再試合するか、ステータスを調整できます。':'同じ試合シードなら結果を再現できます。';$('kill-ranking').innerHTML=killRanking();$('survival-ranking').innerHTML=survivalRanking();$('result').classList.remove('hidden');}
function toSetup(){halt();started=false;world=null;$('setup').classList.remove('hidden');$('result').classList.add('hidden');$('kill-ranking').replaceChildren();$('survival-ranking').replaceChildren();canvas.parentElement.classList.remove('playing');$('pause').disabled=true;$('stop').disabled=true;$('match-state').textContent='参加者を選択';$('time').textContent='00:00';$('seed-display').textContent='';preview();}
$('start').onclick=start;$('pause').onclick=()=>{if(!started||world.finished)return;if(running){halt();$('pause').textContent='再開';$('match-state').textContent='一時停止';}else{running=true;$('pause').textContent='一時停止';$('match-state').textContent='戦闘中';raf=requestAnimationFrame(frame);}};$('stop').onclick=toSetup;$('again').onclick=toSetup;
$('names').addEventListener('input',preview);$('seed').addEventListener('input',preview);$('sudden-death').addEventListener('change',preview);$('random').onclick=()=>setNames(rosterRandom(roster,20));$('random60').onclick=()=>setNames(rosterRandom(roster,60));$('random5').onclick=()=>setNames(rosterRandom(roster,5));$('random2').onclick=()=>setNames(rosterRandom(roster,2));
for(const button of document.querySelectorAll('[data-grade]'))button.onclick=()=>setNames(rosterRandom(profiles.filter(p=>p.grade===button.dataset.grade),5,button.dataset.grade==='5'));
for(const button of document.querySelectorAll('[data-grade-all]'))button.onclick=()=>setNames(profiles.filter(p=>p.grade===button.dataset.gradeAll&&p.id!=='empress').map(p=>p.name));
const catalogForms=new Map();let catalogPress=null,catalogSuppress=null;
const finalFor=id=>profiles.find(p=>p.finalMode&&p.baseId===id);
function catalogRender(){const query=$('search').value.normalize('NFKC').toLowerCase(),current=parse($('names').value),matches=p=>(p.name+' '+p.realName+' '+p.title+' '+p.sourceAbility+' '+p.club).normalize('NFKC').toLowerCase().includes(query);
 visible=roster.map(base=>{const final=finalFor(base.id);if(!final)return base;const selectedFinal=current.some(n=>find(n)?.id===final.id),selectedBase=current.some(n=>find(n)?.id===base.id);let useFinal=catalogForms.has(base.id)?catalogForms.get(base.id):selectedFinal&&!selectedBase;if(query&&matches(final)&&!matches(base))useFinal=true;return useFinal?final:base;}).filter(p=>matches(p)||(p.finalMode&&matches(roster.find(b=>b.id===p.baseId))));
 $('catalog-status').textContent=`${visible.length}人表示 / ${current.length}人選択 / 最大60人`;
 $('catalog-grid').innerHTML=visible.map(p=>{const baseId=p.baseId||p.id,hasFinal=Boolean(finalFor(baseId));return `<button class="catalog-card ${current.some(n=>find(n)?.id===p.id)?'selected':''} ${p.finalMode?'final-mode':''}" data-id="${p.id}" data-base-id="${baseId}" aria-pressed="${current.some(n=>find(n)?.id===p.id)}"${hasFinal?' title="長押し・Shift+Enterで通常版と最終モードを切り替え"':''}>${portrait(p)}<span><strong>${esc(p.name)}</strong><small>G ${esc(p.grade)} · ${esc(p.sourceAbility)}</small>${hasFinal?'<small class="final-hint">'+(p.finalMode?'最終モード · 長押しで通常版':'長押しで最終モード +')+'</small>':''}</span></button>`;}).join('');}
function cancelCatalogPress(){if(catalogPress)clearTimeout(catalogPress.timer);catalogPress=null;}
function switchCatalogForm(card){const current=profiles.find(p=>p.id===card.dataset.id),base=roster.find(p=>p.id===card.dataset.baseId),final=finalFor(base?.id);if(!final)return;
 const next=current.finalMode?base:final,ns=parse($('names').value),selected=ns.some(n=>find(n)?.id===current.id),already=ns.some(n=>find(n)?.id===next.id);
 catalogForms.set(base.id,next.finalMode===true);
 if(selected)setNames([...new Set(ns.map(n=>find(n)?.id===current.id?next.name:n))]);else if(!already&&ns.length<60)setNames([...ns,next.name]);
 catalogRender();[...$('catalog-grid').querySelectorAll('button[data-base-id]')].find(b=>b.dataset.baseId===base.id)?.focus({preventScroll:true});if(!selected&&!already&&ns.length>=60)$('catalog-status').textContent='最大60人です。選択済みのキャラを外してください。';}
$('roster-open').onclick=()=>{cancelCatalogPress();catalogSuppress=null;catalogForms.clear();catalogRender();$('catalog').showModal();};$('search').oninput=()=>{cancelCatalogPress();catalogRender();};
$('catalog-grid').onpointerdown=e=>{cancelCatalogPress();catalogSuppress=null;const card=e.target.closest('button[data-id]');if(!card||!finalFor(card.dataset.baseId)||e.button!==0||e.isPrimary===false)return;
 const press={card,pointerId:e.pointerId,x:e.clientX,y:e.clientY,timer:null};catalogPress=press;try{card.setPointerCapture?.(e.pointerId);}catch{}
 press.timer=setTimeout(()=>{if(catalogPress!==press)return;catalogPress=null;catalogSuppress={baseId:card.dataset.baseId,until:Date.now()+1000};switchCatalogForm(card);},600);};
$('catalog-grid').onpointermove=e=>{if(catalogPress&&e.pointerId===catalogPress.pointerId&&Math.hypot(e.clientX-catalogPress.x,e.clientY-catalogPress.y)>10)cancelCatalogPress();};
$('catalog-grid').onpointerup=cancelCatalogPress;$('catalog-grid').onpointercancel=cancelCatalogPress;$('catalog-grid').onlostpointercapture=cancelCatalogPress;
$('catalog-grid').oncontextmenu=e=>{if(finalFor(e.target.closest('button[data-id]')?.dataset.baseId))e.preventDefault();};
$('catalog-grid').onkeydown=e=>{catalogSuppress=null;const card=e.target.closest('button[data-id]');if(card&&!e.repeat&&e.shiftKey&&(e.key==='Enter'||e.key===' ')&&finalFor(card.dataset.baseId)){e.preventDefault();cancelCatalogPress();switchCatalogForm(card);}};
$('catalog').addEventListener('close',cancelCatalogPress);
$('catalog-grid').onclick=e=>{const b=e.target.closest('button[data-id]');if(!b)return;if(catalogSuppress&&catalogSuppress.baseId===b.dataset.baseId&&Date.now()<catalogSuppress.until){catalogSuppress=null;e.preventDefault();return;}const p=profiles.find(p=>p.id===b.dataset.id);const ns=parse($('names').value);if(ns.some(n=>find(n)?.id===p.id))setNames(ns.filter(n=>find(n)?.id!==p.id));else if(ns.length<60)setNames([...ns,p.name]);else $('catalog-status').textContent='最大60人です。選択済みのキャラを外してください。';catalogRender();};
$('select-visible').onclick=()=>{setNames(rosterRandom(visible));catalogRender();};for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();
function openDetail(name){editedName=name;const r=resolve(name),s={...r.stats,...overrides[name]},p=r.profile,a=profiles.find(p=>p.id===(uniformSkill||s.skill||r.skill));$('detail-name').textContent=name;$('detail-grade').textContent=p?'GRADE '+p.grade+' / '+p.club:'FREE ENTRY / 名前から固定能力';$('detail-real').textContent=p?.realName||'自由入力キャラの基礎値は ATK 18 / HP 1250 / SPD 5.5';$('detail-ability').textContent=a.title;const fighter=world?.units.find(f=>!f.minion&&f.name===name&&f.skill===a.id);$('detail-desc').textContent=a.desc+(a.id==='empress'&&fighter?'\n'+(started?'この試合での能力：':$('seed').value.trim()?'選択中の能力：':'仮抽選の能力（開始時に試合シードで抽選）：')+powerSummary(fighter):'');$('detail-meta').textContent=p?`名鑑の能力：${p.sourceAbility} / 身長 ${p.height}cm / 数値はシミュレーター用の推定値`:'同じ名前なら、参加者や入力順に関係なく同じ能力と基礎値になります。';$('atk').value=s.atk;$('hp').value=s.hp;$('spd').value=s.speed;$('skill').value=uniformSkill||s.skill||r.skill;$('skill').disabled=Boolean(uniformSkill);$('detail-uniform-note').classList.toggle('hidden',!uniformSkill);$('detail-source').classList.toggle('hidden',!p);$('detail-source').href=p?'https://ginghum.github.io/START/characters/'+(p.baseId||p.id)+'.html':'#';$('detail').showModal();}
$('participants').onclick=e=>{const b=e.target.closest('button[data-name]');if(b)openDetail(b.dataset.name);};
$('skill').innerHTML=profiles.map(p=>`<option value="${p.id}">${esc(p.name)} — ${esc(p.title)}</option>`).join('');$('skill').onchange=()=>{const a=profiles.find(p=>p.id===$('skill').value);$('detail-ability').textContent=a.title;const fighter=world?.units.find(f=>!f.minion&&f.name===name&&f.skill===a.id);$('detail-desc').textContent=a.desc+(a.id==='empress'&&fighter?'\n'+(started?'この試合での能力：':$('seed').value.trim()?'選択中の能力：':'仮抽選の能力（開始時に試合シードで抽選）：')+powerSummary(fighter):'');};
$('uniform-skill').innerHTML=$('skill').innerHTML;$('uniform-skill').value='plus';
$('uniform-apply').onclick=()=>{const id=$('uniform-skill').value;if(!profiles.some(p=>p.id===id))return;uniformSkill=id;preview();};
$('uniform-clear').onclick=()=>{uniformSkill='';preview();};
$('edit-form').onsubmit=e=>{e.preventDefault();const atk=Number($('atk').value),hp=Number($('hp').value),speed=Number($('spd').value);if(![atk,hp,speed].every(Number.isFinite)||atk<1||atk>1000||hp<1||hp>100000||speed<.1||speed>30)return;const skill=uniformSkill?(overrides[editedName]?.skill||resolve(editedName).skill):$('skill').value;overrides[editedName]={atk,hp,speed,skill};persist();$('detail').close();if(!started)preview();};
$('restore').onclick=()=>{delete overrides[editedName];persist();$('detail').close();if(!started)preview();};$('reset').onclick=()=>{overrides=Object.create(null);persist();if(!started)preview();};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)$('pause').click();});document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select,button')||document.querySelector('dialog[open]'))return;if(e.code==='Space'&&started&&!world.finished){e.preventDefault();$('pause').click();}});
load();preview();
