'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('jsdom');
const base=path.join(__dirname,'..');const html=fs.readFileSync(path.join(base,'index.html'),'utf8');
const dom=new JSDOM(html,{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,d=w.document;let frames=new Map(),counter=0;
const zooms=[],faceDraws=[],imageLoads=[];w.Path2D=class{constructor(path){this.path=path;}};w.Image=class{set src(src){this._src=src;imageLoads.push(this);}get src(){return this._src;}};w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({},{get:(_,method)=>(...args)=>{if(method==='scale')zooms.push(args);if(method==='drawImage')faceDraws.push(args);},set:()=>true});w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};w.requestAnimationFrame=fn=>{frames.set(++counter,fn);return counter;};w.cancelAnimationFrame=id=>frames.delete(id);
for(const f of ['data.js','engine.js','icons.js','app.js'])w.eval(fs.readFileSync(path.join(base,f),'utf8')+(f==='app.js'?'\nwindow.inspect=()=>({world,overrides,finish});':''));
const el=id=>d.getElementById(id),click=id=>{el(id).click();if(['random','random60','random5','select-visible'].includes(id)||id.startsWith('grade-random-'))assert(!(w.inspect().world?.units||[]).some(f=>f.profile?.id==='empress'),'ランダム選択はエンプレスを除外');};const fill=(id,value)=>{el(id).value=value;el(id).dispatchEvent(new w.Event('input'));};
assert.equal(Object.keys(w.KASU_ICONS.characters).length,93);assert.equal(d.querySelectorAll('.participant .face-sprite').length,8);assert.equal(d.querySelectorAll('clipPath').length,93);for(const p of w.KASU_ROSTER)assert(w.KASU_ICONS.characters[p.id]);imageLoads[0].onload();assert(faceDraws.length>0);assert.equal(d.querySelectorAll('.participant').length,8);click('random');assert.equal(d.querySelectorAll('.participant').length,20);
zooms.length=0;click('random60');assert.equal(d.querySelectorAll('.participant').length,60);assert.equal(w.inspect().world.mode,'normal');assert(!zooms.some(z=>z[0]===1.5&&z[1]===1.5));assert(!zooms.some(z=>z[0]===2&&z[1]===2));zooms.length=0;click('random5');assert.equal(d.querySelectorAll('.participant').length,5);assert(w.inspect().world.smallMode);assert(el('mode-label').textContent.includes('少人数モード'));assert(zooms.some(z=>z[0]===2&&z[1]===2));zooms.length=0;click('council');assert.equal(d.querySelectorAll('.participant').length,12);assert(!w.inspect().world.smallMode);assert(w.inspect().world.mediumMode);assert(el('mode-label').textContent.includes('中人数モード'));assert(zooms.some(z=>z[0]===1.5&&z[1]===1.5));assert(!zooms.some(z=>z[0]===2&&z[1]===2),'中人数モードで2倍にはしない');for(const name of ['カガチ','デビル','ミルク'])assert(!el('names').value.includes(name));assert(el('names').value.split('、').includes('X'));assert(!el('names').value.includes('X（エックス）'));click('roster-open');assert.equal(d.querySelectorAll('.catalog-card').length,93);fill('search','雷を操る');assert.equal(d.querySelectorAll('.catalog-card').length,1);fill('search','エンプレス');assert.equal(d.querySelectorAll('.catalog-card').length,1);click('select-visible');assert.equal(el('names').value,'');assert(el('start').disabled);d.querySelector('[data-close="catalog"]').click();
for(const grade of ['1','2','3','4','5']){click('grade-random-'+grade);const fighters=w.inspect().world.units;assert.equal(fighters.length,5);assert.equal(new Set(fighters.map(f=>f.name)).size,5);assert(fighters.every(f=>f.profile.grade===grade));assert(w.inspect().world.smallMode);}
for(const grade of ['1','2','3','4','5']){click('grade-all-'+grade);const expected=w.KASU_ROSTER.filter(p=>p.grade===grade&&p.id!=='empress');const fighters=w.inspect().world.units;assert.deepEqual(Array.from(fighters,f=>f.profile.id),Array.from(expected,p=>p.id));assert.equal(fighters.length,new Set(fighters.map(f=>f.name)).size);assert(!fighters.some(f=>f.profile.id==='empress'));assert.equal(w.inspect().world.mode,expected.length<=5?'small':expected.length<=20?'medium':'normal');assert(!el('start').disabled);}
fill('names','プラス・ゼロ、ユージ、__proto__、<img src=x onerror=alert(1)>');assert.equal(d.querySelectorAll('.participant').length,4);assert(!d.querySelector('[onerror]'));
d.querySelector('[data-name="__proto__"]').click();fill('atk','24');el('edit-form').dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal(w.inspect().overrides['__proto__'].atk,24);click('reset');assert.equal(Object.keys(w.inspect().overrides).length,0);
fill('names','プラス、ユージ');d.querySelector('[data-name="プラス"]').click();el('skill').value='yuji';el('skill').dispatchEvent(new w.Event('change'));el('edit-form').dispatchEvent(new w.Event('submit',{cancelable:true}));d.querySelector('[data-name="プラス"]').click();assert.equal(el('detail-ability').textContent,'空中の弾き');d.querySelector('[data-close="detail"]').click();click('reset');
// A temporary common ability overlays saved individual skills and stats without storing it.
fill('names','プラス、ユージ、__proto__、架空の参加者');
d.querySelector('[data-name="プラス"]').click();fill('atk','37');fill('hp','1900');fill('spd','4.6');el('skill').value='yuji';el('edit-form').dispatchEvent(new w.Event('submit',{cancelable:true}));
const originalStats=w.inspect().world.units.map(f=>[f.name,f.baseAtk,f.maxHp,f.speed,f.profile?.id]);
assert.equal(el('uniform-skill').options.length,93);assert(el('uniform-clear').disabled);
el('uniform-skill').value='kagachi';click('uniform-apply');assert(w.inspect().world.units.every(f=>f.skill==='kagachi'));assert.deepEqual(w.inspect().world.units.map(f=>[f.name,f.baseAtk,f.maxHp,f.speed,f.profile?.id]),originalStats);assert(!el('uniform-clear').disabled);
el('uniform-skill').value='empress';el('uniform-skill').dispatchEvent(new w.Event('change'));assert(w.inspect().world.units.every(f=>f.skill==='kagachi'),'selecting alone does not apply');click('uniform-apply');assert(w.inspect().world.units.every(f=>f.skill==='empress'&&f.powers.length===5));
el('uniform-skill').value='lance';click('uniform-apply');d.querySelector('[data-name="プラス"]').click();assert.equal(el('skill').value,'lance');assert(el('skill').disabled);assert(!el('detail-uniform-note').classList.contains('hidden'));fill('atk','42');el('edit-form').dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal(w.inspect().overrides['プラス'].skill,'yuji');assert(w.inspect().world.units.every(f=>f.skill==='lance'));assert.equal(w.inspect().world.units.find(f=>f.name==='プラス').baseAtk,42);
const saved=w.localStorage.getItem('kasukou-battle-v1');assert.equal(JSON.parse(saved).overrides['プラス'].skill,'yuji');assert(!Object.hasOwn(JSON.parse(saved),'uniformSkill'));
const reload=new JSDOM(html,{url:'http://localhost/',runScripts:'outside-only'}),rw=reload.window;rw.Image=class{set src(value){}};rw.HTMLCanvasElement.prototype.getContext=()=>new Proxy({},{get:()=>()=>{},set:()=>true});rw.requestAnimationFrame=()=>1;rw.cancelAnimationFrame=()=>{};rw.localStorage.setItem('kasukou-battle-v1',saved);for(const f of ['data.js','engine.js','icons.js','app.js'])rw.eval(fs.readFileSync(path.join(base,f),'utf8')+(f==='app.js'?'\nwindow.inspect=()=>({world,overrides,finish});':''));for(const f of rw.inspect().world.units)assert.equal(f.skill,f.name==='プラス'?'yuji':rw.KasuBattle.resolve(f.name).skill);assert(reload.window.document.getElementById('uniform-clear').disabled);reload.window.close();
click('start');const activeMatch=w.inspect().world;assert(activeMatch.units.every(f=>f.skill==='lance'));d.querySelector('[data-name="プラス"]').click();fill('hp','2300');el('edit-form').dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal(activeMatch.units.find(f=>f.name==='プラス').maxHp,1900,'editing during a match only changes the next match');click('stop');assert(w.inspect().world.units.every(f=>f.skill==='lance'));assert.equal(w.inspect().world.units.find(f=>f.name==='プラス').maxHp,2300);
click('uniform-clear');assert.equal(w.inspect().world.units.find(f=>f.name==='プラス').skill,'yuji');assert.equal(w.inspect().world.units.find(f=>f.name==='プラス').baseAtk,42);d.querySelector('[data-name="プラス"]').click();assert(!el('skill').disabled);assert(el('detail-uniform-note').classList.contains('hidden'));d.querySelector('[data-close="detail"]').click();
el('uniform-skill').value='hat';click('uniform-apply');click('random5');assert(w.inspect().world.units.every(f=>f.skill==='hat'),'new random participants also use the temporary common skill');click('grade-all-5');assert(w.inspect().world.units.every(f=>f.skill==='hat'));assert.equal(w.inspect().world.units.length,21);assert(!w.inspect().world.units.some(f=>f.profile.id==='empress'));click('uniform-clear');click('reset');
fill('names',Array.from({length:61},(_,i)=>'参加者'+i).join(','));assert(el('start').disabled);fill('names',Array.from({length:60},(_,i)=>'参加者'+i).join(','));assert(!el('start').disabled);fill('seed','ui-repeat');el('sudden-death').checked=false;el('sudden-death').dispatchEvent(new w.Event('change'));assert(!w.inspect().world.suddenDeath);assert.equal(JSON.parse(w.localStorage.getItem('kasukou-battle-v1')).suddenDeath,false);assert(el('sudden-caption').textContent.includes('サドンデスなし'));el('speed').value='8';click('start');assert(!w.inspect().world.suddenDeath);assert.equal(frames.size,1);
function tick(ts){const f=[...frames.values()];frames.clear();for(const fn of f)fn(ts);}
let now=0;for(let i=0;i<10;i++)tick(now+=16.67);click('pause');const paused=w.inspect().world.time;tick(now+=1000);assert.equal(w.inspect().world.time,paused);assert.equal(frames.size,0);click('pause');assert.equal(frames.size,1);click('stop');assert.equal(frames.size,0);assert(!el('setup').classList.contains('hidden'));
el('sudden-death').checked=true;el('sudden-death').dispatchEvent(new w.Event('change'));assert(w.inspect().world.suddenDeath);
for(let match=0;match<3;match++){click('random');click('start');for(let i=0;i<1500&&!w.inspect().world.finished;i++)tick(now+=100);assert(w.inspect().world.finished);assert.equal(frames.size,0);assert(!el('result').classList.contains('hidden'));assert.equal(w.inspect().world.effects.length,0);click('again');assert(!el('setup').classList.contains('hidden'));}
// Results rank all real participants by kills, including eliminated fighters, with ties and escaped names.
fill('names','プラス、ユージ、ランス、コンケ、__proto__、<img src=x onerror=alert(1)>');click('start');
const leaderboardMatch=w.inspect().world,killValues=[4,6,6,0,9,2];leaderboardMatch.units.forEach((f,i)=>{f.kills=killValues[i];f.alive=i===3;f.deathTime=[10,45,45,null,20,55][i];});leaderboardMatch.units.push({id:999,name:'召喚物',minion:true,kills:999,alive:false});leaderboardMatch.finished=true;leaderboardMatch.result={winner:leaderboardMatch.units[3],draw:false,timeout:false,time:60};w.inspect().finish();
assert.deepEqual([...d.querySelectorAll('.kill-name')].map(e=>e.textContent),['__proto__','ユージ','ランス','プラス','<img src=x onerror=alert(1)>']);assert.deepEqual([...d.querySelectorAll('.kill-row')].map(e=>e.dataset.rank),['1','2','2','4','5']);assert.deepEqual([...d.querySelectorAll('.kill-count')].map(e=>e.textContent),['9キル','6キル','6キル','4キル','2キル']);assert.equal(el('winner-name').textContent,'コンケ');assert.deepEqual([...d.querySelectorAll('.survival-name')].map(e=>e.textContent),['コンケ','<img src=x onerror=alert(1)>','ユージ','ランス','__proto__']);assert.deepEqual([...d.querySelectorAll('.survival-row')].map(e=>e.dataset.rank),['1','2','3','3','5']);assert.deepEqual([...d.querySelectorAll('.survival-time')].map(e=>e.textContent),['60.0秒・生存','55.0秒','45.0秒','45.0秒','20.0秒']);assert(!d.querySelector('[onerror]'));click('again');assert.equal(el('kill-ranking').children.length,0);assert.equal(el('survival-ranking').children.length,0);
for(const [names,draw,timeout] of [['プラス、ユージ',true,false],['プラス、ユージ、ランス、コンケ',false,true]]){fill('names',names);click('start');const match=w.inspect().world;match.units.forEach((f,i)=>{f.alive=timeout&&i<2;f.deathTime=f.alive?null:draw?0:i===2?70:40;});match.finished=true;match.result={winner:null,draw,timeout,time:180};w.inspect().finish();assert.equal(el('result-title').textContent,draw?'DRAW':'TIME LIMIT');assert.equal(el('kill-ranking').children.length,match.units.length);assert([...d.querySelectorAll('.kill-row')].every(e=>e.dataset.rank==='1'));assert.equal(el('survival-ranking').children.length,match.units.length);assert.deepEqual([...d.querySelectorAll('.survival-row')].map(e=>e.dataset.rank),draw?['1','1']:['1','1','3','4']);assert.deepEqual([...d.querySelectorAll('.survival-time')].map(e=>e.textContent),draw?['0.0秒','0.0秒']:['180.0秒・生存','180.0秒・生存','70.0秒','40.0秒']);click('again');assert.equal(el('kill-ranking').children.length,0);assert.equal(el('survival-ranking').children.length,0);}
console.log('PASS UI (jsdom): presets / all five grade cohorts excluding Empress / temporary common skills / reload and edit preservation / search / free names / edit / 60 limit / pause / 8× / three rematches / effects cleanup / top 5 kill and survival ranks / ties / draw / timeout');dom.window.close();
